# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nom')),
                ('code', models.CharField(max_length=5)),
                ('sort', models.CharField(blank=True, max_length=5, verbose_name='tri')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
    ]
