# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assc', '0002_auto_20170612_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nom'),
        ),
    ]
