# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assc', '0003_auto_20170612_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_hours', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('Nor', 'Normal'), ('CIE', 'Cours IE')], max_length=20)),
            ],
            options={
                'ordering': ('semestre',),
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
                ('code', models.CharField(max_length=5)),
                ('ordering_field', models.IntegerField()),
            ],
            options={
                'ordering': ('ordering_field',),
            },
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('ordering_field',)},
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='sort',
            new_name='ordering_field',
        ),
        migrations.AddField(
            model_name='situation',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assc.Domain'),
        ),
        migrations.AddField(
            model_name='cours',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assc.Semestre'),
        ),
        migrations.AddField(
            model_name='cours',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assc.Situation'),
        ),
    ]
