# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assc', '0004_auto_20170613_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='cie1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='cie2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='cie3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='cie4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='cie5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='cie6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='sem1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='sem2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='sem3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='sem4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='sem5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='sem6',
            field=models.IntegerField(default=0),
        ),
    ]
