# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assc', '0005_auto_20170614_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='practice1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='situation',
            name='practice2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='situation',
            name='practice3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='situation',
            name='practice4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='situation',
            name='practice5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='situation',
            name='practice6',
            field=models.BooleanField(default=False),
        ),
    ]
